### ISSUE TITLE
Unable to run task

### ISSUE THREAD

**Issue by frufru666** [yannickglt/alfred-slack#70]
Anytime I try to run the extension I get

<img width="277" alt="Screen Shot 2021-11-08 at 12 34 44" src="https://user-images.githubusercontent.com/33035240/140735131-c40feedf-7493-48fc-840b-8d7e77430860.png">

**Comment by juanultimate** [comment]
It seems you do not have PHP installed on your mac

**Comment by frufru666** [comment]
I have installed it again, now the workflow doesn't run at all. I get the following in the console: 

```
[09:43:25.378] Slack[Script Filter] Queuing argument 'o'
[09:43:25.556] Slack[Script Filter] Script with argv '(null)' finished
[09:43:25.556] ERROR: Slack[Script Filter] Code 255: PHP Deprecated:  Return type of AlfredSlack\Libs\Route::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Route.php on line 29
Cache folder: /Users/phylyp/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.yannickglt.alfred2.slack
Data folder: /Users/phylyp/Library/Application Support/Alfred/Workflow Data/com.yannickglt.alfred2.slack
ACTION: AlfredSlack\Controllers\ChannelController::getChannelsAction()
SIMULATE: php -r '$query="{\"controller\":\"channel\",\"action\":\"getChannels\",\"params\":{\"channel\":\"o\"}}";include "scripts/index.php";';
PHP Fatal error:  Uncaught Error: Unknown named parameter $channel in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php:24
Stack trace:
#0 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php(24): call_user_func_array(Array, Array)
#1 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(33): AlfredSlack\Controllers\Controller->dispatch('getChannelsActi...', Array)
#2 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(15): AlfredSlack\Libs\Bootstrap->invoke(Object(AlfredSlack\Libs\Route))
#3 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/index.php(13): AlfredSlack\Libs\Bootstrap->run(Object(AlfredSlack\Libs\Query))
#4 Command line code(3): require_once('/Users/phylyp/A...')
#5 {main}
  thrown in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php on line 24
[09:43:25.561] Slack[Script Filter] Deprecated: Return type of AlfredSlack\Libs\Route::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Route.php on line 29

Fatal error: Uncaught Error: Unknown named parameter $channel in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php:24
Stack trace:
#0 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php(24): call_user_func_array(Array, Array)
#1 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(33): AlfredSlack\Controllers\Controller->dispatch('getChannelsActi...', Array)
#2 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(15): AlfredSlack\Libs\Bootstrap->invoke(Object(AlfredSlack\Libs\Route))
#3 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/index.php(13): AlfredSlack\Libs\Bootstrap->run(Object(AlfredSlack\Libs\Query))
#4 Command line code(3): require_once('/Users/phylyp/A...')
#5 {main}
  thrown in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php on line 24
[09:43:25.562] ERROR: Slack[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Deprecated: Return type of AlfredSlack\Libs\Route::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Route.php on line 29

Fatal error: Uncaught Error: Unknown named parameter $channel in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php:24
Stack trace:
#0 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php(24): call_user_func_array(Array, Array)
#1 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(33): AlfredSlack\Controllers\Controller->dispatch('getChannelsActi...', Array)
#2 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/libs/Bootstrap.php(15): AlfredSlack\Libs\Bootstrap->invoke(Object(AlfredSlack\Libs\Route))
#3 /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/index.php(13): AlfredSlack\Libs\Bootstrap->run(Object(AlfredSlack\Libs\Query))
#4 Command line code(3): require_once('/Users/phylyp/A...')
#5 {main}
  thrown in /Users/phylyp/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.86E6A2B6-F9D9-4D2E-9315-5CFD78D9CFC2/scripts/controllers/Controller.php on line 24
```

**Comment by renzo-blockchain** [comment]
The same here :( 

Unable to run task!
Reason: launch path not accessible `/usr/bin/php` Check that the selected language exists on your system. If you're syncing Alfred's preferences, also check that all related workflow files exist locally. 

Related Workflow Info..
Name: 'Slack'
Folder:/Users/$HOME/Library/ApplicationSupport/Alfred/Alfred.alfredpreferences/workflows/user.workflow.35CE167F-D7EF-427D-8656-B2A256C66537


I can see that I do have PHP installed correctly
<img width="269" alt="image" src="https://user-images.githubusercontent.com/2055407/165566688-ae6edfe7-36d7-4a08-9213-705f82fb10b6.png">

**Comment by G3TG0T** [comment]
I have this same issue. I received OPs same error. Now I can't trigger the setup anymore. If I type "slack --add" it just Googles "slack --add"
